name: Call external workflow

on:
  workflow_dispatch:

jobs:
  workflow-call:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow from vrdominguez/test-action-helmfile
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31
        with:
          repo: vrdominguez/test-action-helmfile
          workflow: Prueba instalador helm
          token: ${{ secrets.CALLER_TOKEN }}
          wait-for-completion: false
