name: Prueba instalador helm

on:
  workflow_dispatch:

jobs:
  workflow-call:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow from vrdominguez/test-action-helmfile
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          repo: vrdominguez/test-action-helmfile
          workflow: Prueba instalador helm
          token: ${{ secrets.CALLER_TOKEN }}
          wait-for-completion: false