name: Call external workflow and wait

on:
  workflow_dispatch:

jobs:
  workflow-call:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow from vrdominguez/test-action-helmfile
        id: call-workflow
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          repo: vrdominguez/test-action-helmfile
          workflow: Prueba instalador helm
          token: ${{ secrets.CALLER_TOKEN }}
      
      - name: Check status
        if: always()
        run: |
          echo "Workflow status is: ${{ steps.call-workflow.outputs.workflow-conclusion }}"
          echo ""
          echo "Workflow URL is: ${{ steps.call-workflow.outputs.workflow-url }}"
      
